from logging import Logger
from typing import List
#from examples.stg.project_dag.stg_settings_repository import EtlSetting, StgEtlSettingsRepository
#from lib import VcConnect
#from lib.dict_util import json2str
#from psycopg import Connection
#from psycopg.rows import class_row
from pydantic import BaseModel
import vertica_python
from airflow.decorators import dag, task
import pendulum

@dag(schedule_interval=None, start_date=pendulum.datetime(2022, 5, 5, tz="UTC"))
def sprint6_load_dag():
    conn_info = {
                'host': 'vertica.tgcloudenv.ru',
                'port': '5433',
                'user': 'stv2025021827',
                'password':'aXk5eoCl5d56Mgg',
                'database': 'dwh',
                # autogenerated session label by default,
                'session_label': 'current_session',
                # default throw error on invalid UTF-8 results
                'unicode_error': 'strict',
                # SSL is disabled by default
                'ssl': False,
                # using server-side prepared statements is disabled by default
                'use_prepared_statements': False,
                # connection timeout is not enabled by default
                # 'connection_timeout': 1
            }

    conn = vertica_python.connect(**conn_info)
    @task(task_id="load")
    def load_data():
        cur = conn.cursor()
        cur.execute("""copy STV2025021827__STAGING.dialogs (
            message_id, message_ts, message_from, message_to, message, message_group) 
            from 
            local 'C:\\Users\\Ethan\\Gold_recovery_Project\\project_de\\sprint6\\s6-lessons\\Тема 3.  Разработка аналитической базы данных\\3. Создадим staging-слой\\Задание 2\\dialogs.csv'
            delimiter ',';""")
        conn.commit()

        cur.execute("""copy STV2025021827__STAGING.users (
                    id, chat_name, registration_dt,	country, age) 
                    from 
                    local 'C:\\Users\\Ethan\\Gold_recovery_Project\\project_de\\sprint6\\s6-lessons\\Тема 3.  Разработка аналитической базы данных\\3. Создадим staging-слой\\Задание 2\\users.csv'
                    delimiter ',';""")
        conn.commit()

        cur.execute("""copy STV2025021827__STAGING.groups (
                    id, admin_id int, group_name, registration_dt, is_private) 
                    from 
                    local 'C:\\Users\\Ethan\\Gold_recovery_Project\\project_de\\sprint6\\s6-lessons\\Тема 3.  Разработка аналитической базы данных\\3. Создадим staging-слой\\Задание 2\\groups.csv'
                    delimiter ',';""")
        conn.commit()
    cmd = load_data()
    cmd    
sprint6_load_dag = sprint6_load_dag()
